# Spring boot configuration for recipe data service local profile
# This is used as the default profile if one is not specified at runtime
server:
  port: 9000

spring:
  profiles:
    active: local
    
  devtools:
    restart: 
      enabled: true
      
  datasource:
    url: jdbc:postgresql://localhost:5432/recipemanager
    username: recipemanager
    password: Rec1pemanager!
    driver-class-name: org.postgresql.Driver

  jpa:
    show_sql: true
    
application:
  startup:
    openUrlEnabled: true